include_guard ()

set (Game_SourceFiles
  "Sources/Configuration/Values.hpp"
  "Sources/EventHandling/Commands/Command_Interface.cpp"
  "Sources/EventHandling/Commands/Command_Interface.hpp"
  "Sources/EventHandling/Commands/Commander_Interface.cpp"
  "Sources/EventHandling/Commands/Commander_Interface.hpp"
  "Sources/EventHandling/Commands/CommandNull.cpp"
  "Sources/EventHandling/Commands/CommandNull.hpp"
  "Sources/EventHandling/Commands/MainMenu_Commander.cpp"
  "Sources/EventHandling/Commands/MainMenu_Commander.hpp"
  "Sources/EventHandling/InputEventCallbacks.cpp"
  "Sources/EventHandling/InputEventCallbacks.hpp"
  "Sources/EventHandling/SystemEventCallbacks.cpp"
  "Sources/EventHandling/SystemEventCallbacks.hpp"
  "Sources/GameStates/GameStateManager.cpp"
  "Sources/GameStates/GameStateManager.hpp"
  "Sources/GameStates/GameStateTypes.cpp"
  "Sources/GameStates/GameStateTypes.hpp"
  "Sources/GameStates/MainMenu.cpp"
  "Sources/GameStates/MainMenu.hpp"
  "Sources/Game.cpp"
  "Sources/Game.hpp"
  "Sources/GameFactory.cpp"
)
